server:
  port: 8081
spring:
  cloud: 
   gateway: 
    routes:
      - id: capticketuser
        uri: lb://user/
        predicates:
          - Path=/user/**        
      - id: event
        uri: lb://event/
        predicates:
          - Path=/event/**   
